name: Automatic Workflow Canceller

# This workflow should be triggered in one of three situations:
# 1. Manual workflow dispatch via https://github.com/oppia/oppia-android/actions.
# 2. Upon creation of a PR & updates to that PR.
# 3. Whenever the develop branch is changed (e.g. after a PR is merged).
#
# Note that the action being used here automatically accounts for the current branch & the commit
# hash of the tip of the branch to ensure it doesn't cancel previous workflows that aren't related
# to the branch being evaluated.
on:
  workflow_run:
    workflows: ["Build Tests", "Unit Tests (Robolectric -- Gradle)", "Static Checks", "Unit Tests (Robolectric - Bazel)"]
    types:
      - requested

jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-18.04
    steps:
      # See https://github.com/styfle/cancel-workflow-action#advanced-pull-requests-from-forks for details on this workflow.
      - uses: styfle/cancel-workflow-action@0.8.0
        with:
          workflow_id: ${{ github.event.workflow.id }}
